---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: /path/to/main.go
    ldflags:
      - "-X github.com/veerendra2/gopackages/version.Version={{.Version}}"
      - "-X github.com/veerendra2/gopackages/version.Revision={{.ShortCommit}}"
      - "-X github.com/veerendra2/gopackages/version.Branch={{.Branch}}"
      - "-X github.com/veerendra2/gopackages/version.BuildUser={{envOrDefault 'USER' 'ci'}}"
      - "-X github.com/veerendra2/gopackages/version.BuildDate={{.Date}}"

# Uncomment below to use ko to build distroless image
# kos:
#   - id: distroless-image
#     build: binaries
#     repositories:
#       - ghcr.io/veerendra2/YOUR_REPO_NAME
#     tags:
#       - "{{.Version}}"
#       - latest
#     bare: true
#     preserve_import_paths: false
#     platforms:
#       - linux/amd64
#       - linux/arm64
#     base_image: gcr.io/distroless/static:nonroot

archives:
  - formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
#
# Uncomment and update below to release as Homebrew Cask
# homebrew_casks:
#   - name: YOUR_APP
#     directory: Casks
#     homepage: "https://github.com/veerendra2/YOUR_REPO"
#     description: "YOUR DESCRIPTION"
#     url:
#       verified: github.com/veerendra2/YOUR_REPO
#       template: "https://github.com/veerendra2/YOU_REPO/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     hooks:
#       post:
#         install: |
#           if OS.mac?
#             system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/YOUR_APP"]
#           end
#     repository:
#       owner: veerendra2
#       name: homebrew-tap
#       branch: main
#       token: "{{ .Env.GITHUB_TOKEN }}"
